
# Options taken from https://github.com/rust-lang/rustfmt/blob/master/Configurations.md

brace_style = "AlwaysNextLine"
max_width = 130
merge_imports = true
reorder_impl_items = true
tab_spaces = 4
use_field_init_shorthand = true
