[package]
name = "rust_lang_journey"
version = "0.1.0"
authors = ["devisions <marius.ileana@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[[bin]]
name = "borrowing_ex1"
path = "src/borrowing_ex1.rs"
