version: "3.6"

services:
  postgres:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_USER: todo_actix
      POSTGRES_PASSWORD: todo_actix
      POSTGRES_DB: todo_actix
    ports:
    - 5432:5432
